version: '3.1'

services:
  frontend:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/workspace:delegated

networks:
  default:
    external:
      name: jakirejon-backend_app-net