name: Continous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout the repo
        uses: actions/checkout/@v2
      -
        name: Install dependencies
        run: npm install
      -
        name: Unit tests
        run: npm test
        env:
          CI: true